### PR TITLE
SLING-12186 Enforce source code formatting with spotless-maven-plugin

### PR DESCRIPTION
**Pull request by kwin**
Use Palantir Java Formatter and Sort POM plugin

### CODE REVIEW

**Review by rombert — COMMENTED** [review]
Should there be a .git-blame-ignore-revs as hinted in the Jira issue?

**Comment by kwin** [comment]
The .git-blame-ignore-revs can only be committed after the merge (as that changes commit ids with squash or rebase).

**Comment by stefanseifert** [comment]
can we also create a how-to document/wiki page what to do:

* initially when switchting to this new parent which enforces the formatting to ensure existing code is complient
* and later when contributing new code/PRs and build starts failing do to formatting violation
* and maybe even some hints/links how to include the formatting rules in the IDEs

**Comment by kwin** [comment]
I can still create a wiki page regarding how to use that feature with some of the aforementioned links. @stefanseifert Any general concerns with going forward like this?

**Pull request merged**
